# Generated by Django 3.1.6 on 2021-02-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementapp', '0002_auto_20210227_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='session_end_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='session_start_year',
            field=models.DateField(null=True),
        ),
    ]
